default_install_hook_types:
    - pre-push

repos:
    - repo: local
      hooks:
          - id: bazel-format
            name: Format
            entry: bazel run //:format
            language: system
            stages: [pre-push]
            pass_filenames: true
